### PR TITLE
fix(http): #12 Remove ScopedHttpClient

### LINKED ISSUE #12: Remove node-scoped-http-client
Original issue
https://github.com/hubotio/hubot/issues/1485

from @sschueller

The Library node-scoped-http-client is an unmaintained security risk. Last commit was 5 Jun 2015 and the maintainer is giving access to npmjs to anyone who is interested.

### PR DESCRIPTION
**Pull request by joeyguerra**

### CODE REVIEW

**Review by xurizaemon — APPROVED** [review]
AFAICT we're taking https://github.com/technoweenie/node-scoped-http-client/blob/master/src/index.coffee, converting it to JS, and adding it to this package.

The reason we're doing this is that one of Hubot's interfaces is providing an HTTP client with scoping behaviour, and that scoped client package is unmaintained and has a risky policy to granting maintainership to anyone.

TBH I'd prefer we NOT copy in a bunch of code for this (eg if there was a supported alternative library?) but I don't know there is one, and this is a reasonable step in the interim (better than depending on something which could turn bad tomorrow).

There's also the question of who owns copyright for that new `src/httpclient.js` new file? If it's a straight coffee > js of that linked file above, I believe that the code would remain (c) Technoweenie. I believe that's also fine per license compatibility but I'm not expert at that side of things - for maintenance/security that forks additional code into this repo?

**Comment by xurizaemon** [comment]
This also needs an update to "Making HTTP calls" in https://github.com/hubot-new/hubot/blob/master/docs/scripting.md

**Comment by joeyguerra** [comment]
Yes, I just used an online converter to convert it to JavaScript from CoffeeScript. I've added the MIT License from the scoped-http-client repo in an effort to be compliant.

I believe we'll have to update all the docs, replacing examples and copy of CoffeeScript with JavaScript. I figured we could do that next.

**Comment by joeyguerra** [comment]
The tests are failing because the code is now using a newer version of `standard` but doesn't have all of the fixes from a previous PR. I'm going to close this PR and create a new one from the latest `master` to deal with this issue. I don't want to `git rebase origin/master` because I think there will be a ton of changes from all the merged PRs and I don't want to complicate this one.

**Pull request closed without merging**
