### PR TITLE
fix(tests): Include CI for Windows, OSX

### PR DESCRIPTION
**Pull request by xurizaemon**
Refs #20

The Windows test was uncomfortably slow when I ran it before, compared to the snappy tests so far.

### CODE REVIEW

**Comment by xurizaemon** [comment]
Well, Windows is broken and OSX won't get out of the queue.

**Comment by xurizaemon** [comment]
Ayyy, tests pass on Windows, that wasn't so hard once I had a look 😁

**Comment by xurizaemon** [comment]
To deal with the slowness I've set to run all tests on push to master and a weekly schedule, and just linux on PRs. We should still see it if anything breaks and schedule hopefully tells us if an upstream component does something weird that makes it uninstallable too.

**Comment by joeyguerra** [comment]
I don't know what benefits we get scheduling the pipeline to run compared to when it runs on push to master. But I'm going to merge because the rest looks good to me.

**Comment by xurizaemon** [comment]
I like to test systems which have external integrations from schedule too, since something external to the system under test may change. In this case an example might be if a dependency was _removed_ from NPM and became no longer installable; a scheduled CI run would show that up where a merge to master run might lead you to assume the system broke because of the merge.

It's a bit of an edge case but it has saved me debugging the wrong thing at risk to my sanity at least once.

**Comment by xurizaemon** [comment]
Also I'm way more familiar with Gitlab CI so I'm testing stuff out here :)

**Comment by joeyguerra** [comment]
That makes sense. I was thinking there would be a cost. At least an energy cost. But we'll see.

**Pull request merged**
