### PR TITLE
#45: Github Actions for tests

### PR DESCRIPTION
**Pull request by xurizaemon**
Enabling some initial tests for CI. Refs #45.

- [ ] `npm test` to run tests
- [ ] Review warnings from `npm run test` (see output in actions)
- [ ] `npm audit` to show updates required (which will complain a lot)
- [ ] test generation (https://github.com/hubotio/hubot/issues/1063)

### CODE REVIEW

**Comment by xurizaemon** [comment]
@joeyguerra what do you think the correct action here is?

Github's `actions/setup-node@v3` bails out if the tested package doesn't have a `package-lock.json`.

This repo is intended to be used as a start point, so we _probably_ don't want to commit a `package-lock.json`? I expect that bot instances would then conflict with upstream ... maybe not, since bot instances also modify `package.json`.

In order to progress this I will propose adding a `package-lock.json` in this PR, but I want to explicitly check we agree that's the right thing to do before we merge it.

**Comment by joeyguerra** [comment]
I agree. We should checkin the `package-lock.json` file. It's the community accepted way to address some scenarios where unexpected version changes/breaking changes coming from transient dependencies. We can at least do our part.

**Comment by xurizaemon** [comment]
Ok. I will move that to a separate PR to document this change, then resume the tests. Started doing this, ran out of battery, swapped to doing Easter weekend things :)

(Apologies if I'm too much a nerd about this but occasionally it pays off, bear with me!)

**Comment by joeyguerra** [comment]
Ok.

I think adding `package-lock.json` is the right thing to do.

Yeah, Easter. We're trying to wrap up remodeling work AND THEN clean up to prepare for company. Super fun!!! Why do we do this to ourselves ;)

**Comment by joeyguerra** [comment]
I created an issue for the lock file: https://github.com/hubot-new/hubot/issues/32

**Comment by xurizaemon** [comment]
This as-is gives us test coverage at least. Have added v latest per https://github.com/hubot-new/hubot/issues/33#issuecomment-1499755393

Other items in the tasks here can go to #45. e2e tests can't happen yet so shouldn't block this.

**Comment by joeyguerra** [comment]
Looks good to me. I'm going to smerge it.

**Pull request merged**
