### PR TITLE
fix(adapter): #5 `send` wasn't returning the results from the extending adapter

### LINKED ISSUE #5: Noticed this problem as well when trying to upgrade from 2.9.1 to 3.3.2, and using hubot-slack. In 2.9.1 I had used robot.send to send a message, capture the returned array of promises to get a handle to the message, and then post additional messages in a thread under the first message. Now this no longer works.
from @rajasibero
Noticed this problem as well when trying to upgrade from 2.9.1 to 3.3.2, and using hubot-slack. In 2.9.1 I had used robot.send to send a message, capture the returned array of promises to get a handle to the message, and then post additional messages in a thread under the first message. Now this no longer works.
As xob explained, an easy fix here to restore the old behaviour would be to add the "return" statement in the robot.send function:

send (envelope/* , ...strings */) {
    const strings = [].slice.call(arguments, 1)

    return this.adapter.send.apply(this.adapter, [envelope].concat(strings))
  }
(and the same in robot.messageRoom)

Original issue
https://github.com/hubotio/hubot/issues/1546

### PR DESCRIPTION
**Pull request by joeyguerra**

### CODE REVIEW

**Comment by joeyguerra** [comment]
@xurizaemon Will you please review when you get a moment. No rush.

**Comment by joeyguerra** [comment]
This fixes #9 too.

**Comment by xurizaemon** [comment]
I think this seems reasonable. What I believe we're doing is restoring the behaviour from CoffeeScript's implicit return of last value for those methods, which would have been lost in [the conversion](https://github.com/hubotio/hubot/pull/1347) conversion from CoffeeScript to JavaScript.

- https://github.com/hubotio/hubot/compare/v2.9.3...v3.3.2 is the closest compare URL I can give since tag v2.9.1 isn't in that repo?

It does constitute a change in interface and there's a _chance_ of something being surfaced which folks weren't anticipating here. That should be documented even though it appears reasonable to us.

This led me to open #44.

I think the proposed change here looks good. I'd like us to land test fixes _first_ (so we get alerted if any later PR breaks things), and I'd like us to rebase all PRs (including #30 which I'll do next) to use commit formats which will work for semantic-release (see #44).

**Review by xurizaemon — CHANGES_REQUESTED** [review]
Review is in https://github.com/hubot-new/hubot/pull/34#issuecomment-1500523403

- Commits should be something like `fix(robot): send, messageRoom return value which was returned from adapter (#5, #9)` (I think, see [format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format) expected by semantic-release)

**Pull request closed without merging**
